baseURL = "https://neuro-reasoning-cse.com/"
languageCode = 'en-us'
title = 'Neuro-Reasoning Lab'
theme = 'FixIt'

[params]
  [params.app]
    svgFavicon = "/ai16x16.png"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[menu]
    [[menu.main]]
    identifier = "news"
    name = "News"
    url = 'news'
    weight = 10

    [[menu.main]]
    identifier = "members"
    name = "Members"
    weight = 20

    [[menu.main]]
    identifier = "faculty"
    parent = "members"
    name = "Academics"
    url = 'members/faculty/'
    weight = 21

    [[menu.main]]
    identifier = "students"
    parent = "members"
    name = "Students"
    url = 'members/students/'
    weight = 22

    [[menu.main]]
    identifier = "collaborators"
    parent = "members"
    name = "Collaborators"
    url = 'members/collaborators/'
    weight = 23

    [[menu.main]]
    identifier = "alumni"
    parent = "members"
    name = "Alumni"
    url = 'members/alumni/'
    weight = 24

    [[menu.main]]
    identifier = "research"
    name = "Research"
    url = 'research/'
    weight = 30

    [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = 'projects/'
    weight = 40
